################################################################################
# data
################################################################################
data_location: "/fast/groups/ag_sanders/scratch/suharto_tmp/analysis/p3456_trbc"
manual_selection: ""


################################################################################
# breakpointR params
################################################################################
pairedEndReads: "TRUE"
minReads: 10
maskRegions: ""
reuse_existing_files: "FALSE"
windowsize: 3000000
background: 0.1
binMethod: "size"
pair2frgm: "FALSE"
min_mapq: 10
callHotSpots: "TRUE"
filtAlt: "TRUE"
species: ""




################################################################################
# plotting params
################################################################################
chr_to_exclude: ""
condition_dt: ""
